/* Runs against the actual engine; reusable from tests/index.html or a JS VM. */
(function(root){
const {FruitEngine,BOUNDS,floorY}=root.FruitPhysics,{FRUITS}=root.FruitArt;
const results=[];const check=(v,msg)=>{if(!v)throw Error(msg)};
function test(name,fn){try{fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message})}}
function rng(seed=45){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
const fresh=()=>new FruitEngine({random:rng()});
function run(e,seconds){for(let i=0;i<seconds*120;i++)e.step(1/120)}
test('25 unique fruit types, required fruits, small mangosteen',()=>{check(FRUITS.length===25,'fruit count');check(new Set(FRUITS.map(f=>f.name)).size===25,'duplicate');for(const n of ['Pineapple','Watermelon','Coconut','Cantaloupe','Mangosteen'])check(FRUITS.some(f=>f.name===n),'missing '+n);check(FRUITS.find(f=>f.name==='Mangosteen').radius===23,'mangosteen too large');check(FRUITS.find(f=>f.name==='Watermelon').radius>FRUITS[17].radius*3,'sizes insufficient')});
test('Same-fruit contact merges once and upgrades',()=>{const e=fresh();e.spawn(17,300,460);e.spawn(17,300,410);run(e,2);check(e.merges===1,'merge count');check(e.bodies.length===1&&e.bodies[0].type===18,'upgrade');check(e.score===20,'score')});
test('Different fruits collide without merging',()=>{const e=fresh();e.spawn(17,300,460);e.spawn(5,300,420);run(e,2);check(e.merges===0&&e.bodies.length===2,'unintended merge')});
test('All 25 fruit types merge; terminal pairs become juice',()=>{for(const f of FRUITS){const e=fresh();e.spawn(f.id,330,490,{lock:0});e.spawn(f.id,330,490-f.radius*2+1,{lock:0});run(e,1);check(e.merges===1,'merge missing '+f.name);check(f.tier===7?e.bodies.length===0:e.bodies[0].type===f.id+1,'route '+f.name);check(e.ml>0||e.drops.length>0,'no juice')}});
test('Triple contact never consumes a fruit twice',()=>{const e=fresh();for(let i=0;i<3;i++)e.spawn(17,300+i*31,485,{lock:0});e.step(1/120);check(e.merges===1&&e.bodies.length===2,'duplicate merge')});
test('Mass scales with area; large fruit pushes small fruit',()=>{const e=fresh();const big=e.spawn(4,250,floorY(250)-FRUITS[4].radius*1.027,{vx:170,lock:999});const small=e.spawn(5,329,floorY(329)-17*1.027,{lock:999});const old=small.x;run(e,.9);check(big.m>small.m*10,'mass ratio');check(small.x>old+12,'small fruit not displaced');check(Number.isFinite(big.vx),'invalid motion')});
test('Ground friction converts translation to visible rotation',()=>{const e=fresh();const b=e.spawn(1,230,BOUNDS.floor-51,{vx:210,w:0,angle:0});run(e,1.3);check(b.x>260,'no rolling travel');check(Math.abs(b.angle)>.35,'rotation fixed');check(b.vx<210&&Math.abs(b.w)>0,'friction absent')});
test('Fruit accelerates under gravity and settles at floor',()=>{const e=fresh();const b=e.spawn(9,300,180);run(e,.2);const v=b.vy;run(e,.2);check(b.vy>v+120,'constant speed');run(e,12);check(b.y+b.r<=floorY(b.x)+.3,'floor');check(Math.abs(b.vy)<20,'never settles')});
test('Juice is collected only after falling, gutter and outlet travel',()=>{const e=fresh();e.pulp(90,200,4,36);check(e.ml===0,'instant juice');run(e,.3);check(e.ml===0,'premature collection');let gutter=false,outlet=false;for(let i=0;i<700;i++){e.step(1/120);gutter ||= e.drops.some(p=>p.stage===1);outlet ||= e.drops.some(p=>p.stage===2)}check(gutter&&outlet,'flow path skipped');check(Math.abs(e.ml-36)<.001&&e.drops.length===0,'volume not conserved')});
test('Cup colour mixes by fruit juice volume',()=>{const e=fresh();e.pulp(337,600,4,20);run(e,3);const red=e.mix.slice();e.pulp(337,600,7,60);run(e,3);check(e.ml>79.99,'volume');check(e.mix.some((v,i)=>Math.abs(v-red[i])>15),'unchanged colour')});
test('Juice boost doubles the next three merges and consumes one charge',()=>{const e=fresh();check(e.select('boost'),'activation');check(!e.select('boost'),'stacking');for(let i=0;i<4;i++){const a=e.spawn(17,300,590),b=e.spawn(17,300,550);e.merge(a,b);e.bodies=[]}check(e.boostLeft===0&&e.charges.boost===0,'charges');check(Math.abs(e.drops.reduce((s,p)=>s+p.ml,0)-126)<.001,'boost amount')});
test('Hammer targets exactly one fruit; empty click costs nothing',()=>{const e=fresh();e.spawn(17,250,600);e.spawn(5,450,600);e.select('hammer');check(!e.useAt(100,300),'empty target');check(e.charges.hammer===1,'empty cost');check(e.useAt(250,600),'hit');check(e.bodies.length===1&&e.bodies[0].type===5,'wrong target');check(e.charges.hammer===0&&e.selection===null,'not consumed')});
test('Bomb clears radius targets and preserves distant fruit',()=>{const e=fresh();e.spawn(17,200,580);e.spawn(5,250,580);e.spawn(12,560,580);e.select('bomb');check(e.useAt(225,580),'bomb failed');check(e.bodies.length===1&&e.bodies[0].type===12,'radius');check(e.charges.bomb===0&&e.effects.some(v=>v.kind==='blast'),'feedback');run(e,5);check(e.ml>0,'bomb no juice')});
test('No-charge tools, tool cancel, paused actions',()=>{const e=fresh();e.charges.bomb=0;check(!e.select('bomb'),'empty usable');e.select('hammer');e.select('hammer');check(e.selection===null,'toggle');e.paused=true;check(!e.drop()&&!e.select('boost'),'paused actions');const t=e.time;e.step(.03);check(e.time===t,'pause clock')});
test('Timed pressure still drops fruit while targeting a tool',()=>{const e=fresh();e.started=true;e.select('hammer');e.autoClock=e.interval-.01;run(e,.03);check(e.dropCount===1,'targeting pauses pressure');check(e.selection==='hammer','selection lost')});
test('Difficulty increases, medium fruits drop, bucket width stays fixed',()=>{const e=fresh(),w=BOUNDS.right-BOUNDS.left,t=e.interval;e.dropCount=300;check(e.interval<t,'no pressure');const picks=Array.from({length:200},()=>e.pick());check(picks.some(v=>FRUITS[v].tier===3),'no medium fruits');check(BOUNDS.right-BOUNDS.left===w&&w===495.25,'bucket shrinks')});
test('Danger line ends supported high stack after grace period',()=>{const e=fresh();for(let row=0;row<5;row++)for(let col=0;col<4;col++)e.spawn([4,11,16,24][(row+col)%4],116+col*126,BOUNDS.floor-110-row*122,{age:3,lock:999});run(e,4.5);check(e.ended&&e.danger>=4,'danger did not end');check(!e.drop(),'drop after game over')});
test('Restart resets score, liquid, pressure, bodies, tools and effects',()=>{const e=fresh();e.drop();e.select('boost');e.select('hammer');e.useAt(e.bodies[0].x,e.bodies[0].y);run(e,2);e.score=30;e.ended=true;e.paused=true;e.reset();check(e.score===0&&e.ml===0&&e.merges===0,'scores');check(!e.ended&&!e.paused&&!e.selection,'flags');check(!e.bodies.length&&!e.drops.length&&!e.effects.length,'objects');check(e.charges.boost===1&&e.charges.hammer===1&&e.charges.bomb===1,'tool reset');check(e.autoClock===0&&e.danger===0&&e.cooldown===0,'timers')});
test('Long seeded simulation remains finite and within bucket',()=>{for(let seed=1;seed<=6;seed++){const e=new FruitEngine({random:rng(seed)});for(let frame=0;frame<7200&&!e.ended;frame++){if(frame%75===0)e.drop(90+e.random()*470);if(frame%1500===1000){e.select('bomb');e.useAt(337,450)}e.step(1/120);for(const b of e.bodies)check([b.x,b.y,b.vx,b.vy,b.w].every(Number.isFinite),'nonfinite');}for(const b of e.bodies)check(b.x-b.r>BOUNDS.left-2&&b.x+b.r<BOUNDS.right+2&&b.y+b.r*Math.hypot(1,(BOUNDS.floor-BOUNDS.floorEdge)/((BOUNDS.right-BOUNDS.left)/2))<floorY(b.x)+2,'escaped bounds')}});

test('Container side wall is one third taller with the requested narrower width',()=>{check(Math.abs((BOUNDS.floorEdge-112)/(466-112)-4/3)<.005,'wall height');check(BOUNDS.right-BOUNDS.left===495.25,'width')});
test('Large drop probability stays at 39 percent at all difficulty levels',()=>{for(const late of [false,true]){const e=fresh();if(late)e.dropCount=300;const counts=Array(8).fill(0);for(let i=0;i<20000;i++)counts[FRUITS[e.pick()].tier]++;const big=counts.slice(4).reduce((a,b)=>a+b)/20000;check(Math.abs(big-(.39))<.015,'large share');check((counts[0]+counts[1])/20000<.21,'small share');check(counts[7]>150,'terminal fruit missing')}});
test('Fruit rolls downhill on the visible slope without a flat shelf',()=>{const e=fresh(),b=e.spawn(1,160,390,{angle:0});run(e,2);check(b.x>180&&Math.abs(b.angle)>.2,'not rolling downhill');check(b.y+b.r>BOUNDS.floorEdge,'invisible horizontal shelf')});
test('Sixty merges never refill the three single-use tools',()=>{const e=fresh();e.select('boost');e.charges.hammer=0;e.charges.bomb=0;for(let i=0;i<60;i++){const a=e.spawn(17,300,450),b=e.spawn(17,300,420);e.merge(a,b);e.bodies=[];e.drops=[]}check(Object.values(e.charges).every(n=>n===0),'refilled');check(!e.select('boost')&&!e.select('hammer')&&!e.select('bomb'),'reusable')});
test('No automatic drops before the player starts',()=>{const e=fresh();run(e,30);check(!e.started&&!e.bodies.length&&e.autoClock===0,'started by itself');check(e.drop(),'first drop');check(e.started,'not started')});
test('Large fruits shrink by one third and all routes still grow',()=>{const old=[51,64,78,93];for(const f of FRUITS){if(f.tier>=4)check(Math.abs(f.radius-old[f.tier-4]*2/3)<1e-8,'size reduction');if(f.tier<7)check(FRUITS[f.id+1].radius>f.radius,'merge shrinks fruit')}});
test('Automatic pressure starts at 15 seconds and never faster than 6',()=>{const e=fresh();check(e.interval===15,'start interval');e.dropCount=10000;check(e.interval>=6&&e.interval>4.5,'minimum interval')});
test('Removed fruits never drop or appear as a merge result',()=>{const removed=['Cranberry','Cherry','Strawberry','Banana','Gooseberry','Pear','Guava'];check(!FRUITS.some(f=>removed.includes(f.name)),'removed fruit remains');const e=fresh();for(let i=0;i<10000;i++)check(!removed.includes(FRUITS[e.pick()].name),'removed drop');for(const family of [0,1,2,3]){const route=FRUITS.filter(f=>f.family===family);for(let i=0;i<route.length-1;i++){check(route[i+1].id===route[i].id+1,'broken route');check(route[i+1].radius>route[i].radius,'size reversed')}}});
test('Bowl width is exactly seven eighths of the previous version',()=>{check(Math.abs((BOUNDS.right-BOUNDS.left)/566-.875)<1e-10,'width ratio');check((BOUNDS.right+BOUNDS.left)/2===337,'off center')});
root.engineTestResults=results;
})(typeof window==='undefined'?globalThis:window);
