const fs=require('fs'),vm=require('vm'),path=require('path');const p=path.resolve(__dirname,'..'),results=[];
const check=(b,m)=>{if(!b)throw Error(m)};async function test(name,fn){try{await fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message})}}
(async()=>{
 let calls=[],ticks=new Map(),tid=0;const param=()=>({setValueAtTime(v,t){calls.push(['set',v,t])},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});class AC{constructor(){this.currentTime=0;this.state='suspended';this.destination={}}async resume(){this.state='running'}createGain(){return {gain:param(),connect(){},disconnect(){}}}createOscillator(){return {frequency:param(),connect(){},disconnect(){},start(t){calls.push(['start',t])},stop(t){calls.push(['stop',t])}}}}
 const a=vm.createContext({Math,console,AudioContext:AC,setInterval:fn=>{ticks.set(++tid,fn);return tid},clearInterval:id=>ticks.delete(id)});vm.runInContext(fs.readFileSync(p+'/audio.js','utf8'),a);const audio=new a.FruitAudio({getItem:()=>null,setItem(){}});
 await test('Audio waits for a user unlock before creating a context',()=>check(audio.ctx===null&&ticks.size===0,'autoplay'));
 await test('User unlock schedules original melody and finite envelopes',async()=>{audio.music=true;await audio.unlock();check(calls.some(c=>c[0]==='start'),'silent');check(ticks.size===1,'scheduler');for(const call of calls)check(call.slice(1).every(Number.isFinite),'invalid note')});
 await test('Repeated audio unlock does not duplicate music scheduler',async()=>{await audio.unlock();await audio.unlock();check(ticks.size===1,'duplicate')});
 await test('Music off leaves sound effects available',()=>{audio.toggle('music');check(ticks.size===0&&audio.sfx,'music mute failed');const count=calls.length;audio.effect('merge');check(calls.length>count,'no effect')});
 await test('Sound off mutes effects independently',()=>{audio.toggle('sfx');const count=calls.length;audio.effect('bomb');check(count===calls.length,'sound still on')});
 await test('Pause stops scheduling and resume restores only enabled music',()=>{audio.toggle('music');audio.setPaused(true);check(ticks.size===0,'pause');audio.setPaused(false);check(ticks.size===1,'resume')});
 const shareContext=vm.createContext({Math,console});vm.runInContext(fs.readFileSync(p+'/share.js','utf8'),shareContext);const links=shareContext.FruitShareCard.socialLinks(1234);
 await test('Social destinations encode the actual score and canonical HTTPS URL',()=>{check(new URL(links.x).searchParams.get('url')==='https://fruitmergegame.net/','wrong URL');check(new URL(links.whatsapp).searchParams.get('text').includes('1,234'),'wrong score');check(!links.text.includes('%'),'fabricated percentile')});
 const art=vm.createContext({Math,console});vm.runInContext(fs.readFileSync(p+'/fruits.js','utf8'),art);const find=n=>art.FruitArt.FRUITS.find(f=>f.name===n).id;
 await test('Fruit expressions include grumpy, teary, blinking and impact states',()=>{const f=art.FruitArt.faceState;check(f(find('Apple'),2)==='grumpy','angry');check(f(find('Blueberry'),2)==='teary','crying');check(f(0,0)==='blink','blink');check(f(0,2,.7)==='bump','collision')});
 await test('Ranking names and score rows live outside home document',()=>{const html=fs.readFileSync(p+'/index.html','utf8');check(!html.includes('<tbody')&&!html.includes('id="rankings"'),'inline leaderboard');check(html.includes('data-src="rankings/index.html"'),'eager frame');check(fs.readFileSync(p+'/rankings/index.html','utf8').includes('noindex,nofollow'),'indexable rank page');check(html.indexOf('class="page-intro"')>html.indexOf('id="game"'),'intro above game')});
 fs.writeFileSync(p+'/tests/features-results.json',JSON.stringify(results,null,2));for(const r of results)console.log((r.passed?'PASS ':'FAIL ')+r.name+(r.error?' '+r.error:''));if(results.some(r=>!r.passed))process.exitCode=1;
})();
