(function(root){
const {RunStore,formatTime,KEY}=root.FruitRanking,results=[];
function check(v,message){if(!v)throw Error(message)}
function test(name,fn){try{fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message})}}
function memory(){const values={};return {values,getItem:k=>values[k]??null,setItem:(k,v)=>values[k]=v}}
test('Rankings use highest score first, not juice or insertion order',()=>{const s=new RunStore(memory());for(const [i,score] of [22,350,91].entries())s.add({id:String(i),player:'Player'+i,score});check(s.records.map(r=>r.score).join(',')==='350,91,22','order')});
test('Finished results persist after reloading the store',()=>{const storage=memory(),s=new RunStore(storage);s.add({id:'one',player:'Kiwi',score:272});const reloaded=new RunStore(storage);check(reloaded.records[0].score===272&&reloaded.records[0].player==='Kiwi','not persisted');check(Object.keys(storage.values).join('')===KEY,'unexpected storage keys')});
test('A run cannot be saved twice',()=>{const s=new RunStore(memory());check(s.add({id:'same',score:50}),'first');check(!s.add({id:'same',score:80})&&s.records.length===1,'duplicate')});
test('The fifteen highest results are retained',()=>{const s=new RunStore(memory());for(let i=1;i<=20;i++)s.add({id:String(i),player:'Player'+i,score:i});check(s.records.length===15&&s.records[0].score===20&&s.records[14].score===6,'top ten')});
test('Invalid stored results are ignored and names are bounded',()=>{const m=memory();m.setItem(KEY,JSON.stringify([{id:'valid',player:'A'.repeat(100),score:35},{id:'bad',score:-2},{id:'nan',score:'lots'},{id:'valid',score:999},null]));const s=new RunStore(m);check(s.records.length===1&&s.records[0].player.length===20,'validation')});
test('Blocked storage retains session results and reports the limitation',()=>{const s=new RunStore({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}});check(!s.persistent,'no warning');check(s.add({id:'x',player:'You',score:10})&&s.records.length===1,'lost session data')});
test('Survival time formatting handles minutes and hours',()=>{check(formatTime(272.9)==='04:32','minutes');check(formatTime(3661)==='1:01:01','hours');check(formatTime(-1)==='00:00','negative')});
test('Old volume and time records are not interpreted as scores',()=>{const m=memory();m.setItem('fruit-merge-longest-runs-v2',JSON.stringify([{id:'old',seconds:600}]));const s=new RunStore(m);check(s.records.length===0,'old time treated as score');s.add({id:'juice',score:42});check(JSON.parse(m.values['fruit-merge-longest-runs-v2'])[0].seconds===600,'old data overwritten')});
test('One name keeps only its highest score, including case variants',()=>{const s=new RunStore(memory());s.add({id:'a',player:'Alex',score:100});s.add({id:'b',player:' alex ',score:80});check(s.records.length===1&&s.records[0].score===100,'lower score replaced best');s.add({id:'c',player:'ALEX',score:150});check(s.records.length===1&&s.records[0].score===150,'best not updated')});
test('Legacy duplicate names collapse on load',()=>{const m=memory();m.setItem(KEY,JSON.stringify([{id:'a',player:'Alex',score:10},{id:'b',player:'Alex',score:20}]));const s=new RunStore(m);check(s.records.length===1&&s.records[0].score===20,'migration')});
test('Live scores update a single name without lowering historical best',()=>{const records=[{id:'a',player:'Alex',score:100}];let rows=root.FruitRanking.topScores(records,{id:'b',player:'Alex',score:50,live:true});check(rows.length===1&&rows[0].score===100,'best lowered');rows=root.FruitRanking.topScores(records,{id:'b',player:'Alex',score:150,live:true});check(rows.length===1&&rows[0].score===150&&rows[0].live,'live duplicate');check(records[0].score===100,'history mutated')});
root.rankingTestResults=results;
})(typeof window==='undefined'?globalThis:window);
