const fs=require('fs'),vm=require('vm'),path=require('path'),p=path.resolve(__dirname,'..');
(async()=>{let restores=0,opens=0,run={player:'<Alex>',score:4321},posted=null,download='',copied='',mode='image';const out=[];const check=(b,m)=>{if(!b)throw Error(m)};const test=async(name,fn)=>{try{await fn();out.push({name,passed:true})}catch(e){out.push({name,passed:false,error:e.message})}};
const elements={};const graphics={clearRect(){},drawImage(){},fillText(){},fillRect(){}};const d={getElementById:id=>elements[id]||(elements[id]={open:false,disabled:false,style:{},listeners:{},addEventListener(n,fn){this.listeners[n]=fn},showModal(){this.open=true},close(){this.open=false;this.listeners.close?.()},getContext:()=>graphics,toBlob:cb=>cb(new Blob(['png'],{type:'image/png'})),focus(){},select(){}}),body:{append(){}},createElement:()=>({click(){download=this.download},remove(){}})};
class Img{set src(v){queueMicrotask(()=>this.onload())}}
const nav={clipboard:{async writeText(v){copied=v}},canShare:()=>mode==='image',async share(v){if(mode==='cancel')throw Object.assign(Error(),{name:'AbortError'});posted=v}};
const ctx=vm.createContext({Math,console,Image:Img,Blob,File,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},navigator:nav});vm.runInContext(fs.readFileSync(p+'/share.js','utf8'),ctx);const s=new ctx.FruitShare({document:d,getRun:()=>run,onOpen:()=>{opens++;return ()=>restores++}});
await test('Share creates a native image suitable for long-press saving',async()=>{await s.open();check(opens===1&&elements.shareDialog.open,'no dialog');check(s.blob.type==='image/png'&&elements.shareImage.src==='blob:test'&&!elements.shareImage.hidden,'no native PNG image');check(s.snapshot.score===4321,'wrong score')});
await test('Copy link remains available independently',async()=>{await elements.copyLink.onclick();check(copied==='https://fruitmergegame.net/','clipboard')});
await test('Closing share restores the run and reopening updates its snapshot',async()=>{elements.closeShare.onclick();check(restores===1,'not restored');run={player:'Changed',score:999};await s.open();check(s.snapshot.player==='Changed'&&s.snapshot.score===999,'stale result');elements.closeShare.onclick();check(restores===2,'duplicate restore')});
await test('Share controls precede the native image and removed actions are absent',()=>{const html=fs.readFileSync(p+'/index.template.html','utf8');check(html.indexOf('id="share-x"')<html.indexOf('id="shareImage"'),'social links below image');check(!html.includes('id="nativeShare"')&&!html.includes('id="downloadShare"'),'obsolete buttons');check(!html.includes('id="railArt"')&&html.indexOf('id="playerName"')<html.indexOf('id="scoresFrame"'),'name or decorations')});
fs.writeFileSync(p+'/tests/share-results.json',JSON.stringify(out,null,2));for(const r of out)console.log((r.passed?'PASS ':'FAIL ')+r.name+(r.error?' '+r.error:''));if(out.some(r=>!r.passed))process.exitCode=1;
})();
