/* Lightweight DOM harness: executes real game.js handlers, no browser emulation claim. */
const vm=require('node:vm');
module.exports=function runUI(source,options={}){
 let now=1000,frame;const renderCalls={};const methods=['drawImage','bezierCurveTo','beginPath','arc','fill','stroke','ellipse','save','restore','translate','rotate','scale','moveTo','lineTo','closePath','quadraticCurveTo','clip','roundRect','fillText','clearRect','fillRect','setLineDash'];
 const graphics={createLinearGradient:()=>({addColorStop(){}})};for(const m of methods)graphics[m]=()=>{renderCalls[m]=(renderCalls[m]||0)+1};
 class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.style={};this.dataset={src:'rankings/index.html'};this.listeners={};this.children=[];this.attributes={};this.hidden=false;this.disabled=false;this.open=false;this.textContent=''}addEventListener(n,fn){this.listeners[n]=fn}getAttribute(n){return this.attributes[n]}setAttribute(n,v){this.attributes[n]=v}setPointerCapture(){}replaceChildren(){this.children=[]}append(node){this.children.push(node)}getContext(){return options.createCanvas?(this.realCanvas||(this.realCanvas=options.createCanvas(this.width||760,this.height||843))).getContext("2d"):graphics}getBoundingClientRect(){return {left:0,top:0,width:760,height:843}}focus(){}showModal(){this.open=true}close(){this.open=false;this.listeners.close?.()}trigger(type,data={}){if(this.disabled&&type==='click')return;const e={target:this,button:0,preventDefault(){},...data};this.listeners[type]?.(e);this['on'+type]?.(e)}}
 const elements={},docListeners={};const ids=['gameShell','settingsButton','settingsDialog','closeSettings','fullscreen','shareImage','railArt','music','sound','scoresButton','scoresFrame','scoresDialog','closeScores','shareButton','overlayShare','closeShare','shareDialog','shareURL','shareCanvas','copyLink','downloadShare','nativeShare','shareStatus','share-x','share-facebook','share-whatsapp','score','best','juice','merges','runTime','liveRun','playerName','rankings','emptyRanking','storageNote','canvas','boost','hammer','bomb','boostCount','hammerCount','bombCount','overlay','overlayEyebrow','overlayTitle','overlayText','resume','overlayRestart','message','pause','restart','guideButton','closeGuide','guide','fruitGuide'];
 const buttons=['boost','hammer','bomb','resume','overlayRestart','pause','restart','guideButton','closeGuide'];for(const id of ids)elements[id]=new Element(buttons.includes(id)?'button':id==='canvas'?'canvas':'div');elements.overlay.hidden=true;elements.playerName.tagName='INPUT';elements.playerName.value='You';
 const stageClasses=new Set();const stage={classList:{contains:v=>stageClasses.has(v),add:v=>stageClasses.add(v),remove:v=>stageClasses.delete(v),toggle:v=>stageClasses.has(v)?stageClasses.delete(v):stageClasses.add(v)}};elements.gameShell.classList=stage.classList;const document={body:{style:{}},querySelector:()=>stage,getElementById:id=>{if(!elements[id])throw Error('Unknown element '+id);return elements[id]},createElement:tag=>new Element(tag),addEventListener:(n,fn)=>docListeners[n]=fn,hidden:false};
 const storage={};const context=vm.createContext({console,Math,document,localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v},performance:{now:()=>now},location:{search:'?test'},URLSearchParams,requestAnimationFrame:fn=>frame=fn});context.window=context;
 for(const [name,code] of Object.entries(source))vm.runInContext(code,context,{filename:name});const api=context.fruitTest,e=api.engine,results=[];if(options.inspect)return {api,e,elements,tick:(n=1)=>{for(let i=0;i<n;i++){now+=1000/60;frame(now)}},context};const check=(v,m)=>{if(!v)throw Error(m)};const test=(name,fn)=>{try{api.restart();elements.playerName.value="Player "+results.length;fn();results.push({name,passed:true})}catch(err){results.push({name,passed:false,error:err.message})}};const tick=(n=1)=>{for(let i=0;i<n;i++){now+=1000/60;frame(now)}};
 test('Canvas renderer draws game and 25-fruit guide without API errors',()=>{tick(2);check(renderCalls.fill>100&&renderCalls.fillText>5,'nothing drawn');check(elements.fruitGuide.children.length===4,'routes');check(elements.fruitGuide.children.flatMap(x=>x.children).length===25,'guide count')});
 test('Pointer coordinate mapping drops at clicked location',()=>{elements.canvas.trigger('pointerdown',{clientX:240,clientY:330});check(e.dropCount===1&&Math.abs(e.bodies[0].x-240)<.1,'drop coordinates');tick(30);check(e.bodies[0].y>100,'not moving')});
 test('Boost button activates real effect and pressed/disabled state',()=>{elements.boost.trigger('click');check(e.boostLeft===3&&e.charges.boost===0,'no boost');check(elements.boost.attributes['aria-pressed']==='true'&&elements.boost.disabled,'bad active UI');check(elements.boostCount.textContent==='3 left','bad count')});
 test('Hammer button then canvas click removes target and updates count',()=>{e.spawn(17,300,420);elements.hammer.trigger('click');check(elements.hammer.attributes['aria-pressed']==='true','no selected state');elements.canvas.trigger('pointerdown',{clientX:300,clientY:420});check(e.bodies.length===0&&e.charges.hammer===0,'failed hit');check(elements.hammerCount.textContent==='Used','count stale');check(elements.hammer.attributes['aria-pressed']==='false','selection stale')});
 test('Bomb button then canvas click clears area and produces juice',()=>{e.spawn(17,300,420);e.spawn(5,350,420);elements.bomb.trigger('click');elements.canvas.trigger('pointerdown',{clientX:325,clientY:420});check(e.bodies.length===0&&e.charges.bomb===0,'blast failed');tick(300);check(e.ml>0&&Number(elements.juice.textContent)>0,'juice UI stale')});
 test('Pause overlay stops simulation and resume restores play',()=>{elements.pause.trigger('click');check(e.paused&&!elements.overlay.hidden,'pause failed');const t=e.time;tick(10);check(e.time===t,'pause not frozen');elements.resume.trigger('click');check(!e.paused&&elements.overlay.hidden,'resume failed')});
 test('Keyboard aims, drops, selects and cancels tools',()=>{const key=(key,code=key)=>docListeners.keydown({key,code,target:elements.canvas,preventDefault(){}});const x=e.aim;key('ArrowLeft');key(' ','Space');check(e.dropCount===1&&e.bodies[0].x===x-18,'keyboard drop');key('2');check(e.selection==='hammer','shortcut');key('Escape');check(e.selection===null,'escape')});
 test('Restart button clears score, particles, tools and overlay UI',()=>{e.score=50;e.ml=87;e.drop();elements.boost.trigger('click');elements.pause.trigger('click');elements.restart.trigger('click');check(!e.bodies.length&&!e.drops.length&&e.ml===0&&e.score===0,'state not clear');check(elements.overlay.hidden&&elements.score.textContent==='0'&&elements.juice.textContent==='0','UI not clear');check(elements.boostCount.textContent==='1 use'&&elements.boost.attributes['aria-pressed']==='false','boost stale')});
 test('Fruit guide pauses play and closes without stale pause state',()=>{elements.guideButton.trigger('click');check(e.paused&&elements.guide.open,'guide failed');elements.closeGuide.trigger('click');check(!e.paused&&!elements.guide.open,'guide close failed')});

 test('Run timer starts on first drop, not while waiting',()=>{tick(180);check(e.runTime===0&&elements.runTime.textContent==='00:00','waiting counted');elements.canvas.trigger('pointerdown',{clientX:300,clientY:330});tick(180);check(e.runTime>2.9&&e.runTime<3.1,'active clock');check(!elements.liveRun.textContent.includes('ml'),'juice unit')});
 test('Paused duration and time in guide are excluded from the run',()=>{e.drop();tick(120);const t=e.runTime;elements.pause.trigger('click');tick(240);check(e.runTime===t,'paused count');elements.resume.trigger('click');elements.guideButton.trigger('click');tick(240);check(e.runTime===t,'guide count');elements.closeGuide.trigger('click');tick(120);check(e.runTime>t+1.9&&e.runTime<t+2.1,'resume clock')});
 test('Touch waits for release and drops at the final aim position',()=>{elements.canvas.trigger('pointerdown',{pointerType:'touch',pointerId:1,clientX:200,clientY:300});check(e.dropCount===0,'dropped too early');elements.canvas.trigger('pointermove',{clientX:400,clientY:300});elements.canvas.trigger('pointerup',{clientX:400,clientY:300});check(e.dropCount===1&&e.bodies[0].x===400,'release aim wrong')});
 test('A finished run enters the ranking exactly once and survives restart',()=>{const old=api.rankings.records.length;elements.playerName.value='Lime';e.drop();tick(120);e.ml=123;e.score=123;e.ended=true;api.saveRun();api.saveRun();check(api.rankings.records.length===old+1,'missing or duplicate record');check(api.rankings.records.some(r=>r.player==='Lime'&&r.score===123),'record score/name');elements.restart.trigger('click');check(api.rankings.records.length===old+1,'restart erased records');check(e.runTime===0,'timer did not reset')});
 test('Restarting an unfinished run never adds a ranking',()=>{const n=api.rankings.records.length;e.drop();tick(60);elements.restart.trigger('click');check(api.rankings.records.length===n,'unfinished recorded')});
 test('Typing a name does not trigger gameplay shortcuts',()=>{docListeners.keydown({key:'p',code:'KeyP',target:elements.playerName,preventDefault(){}});check(!e.paused,'name shortcut leaked')});

 test('Last flowing drops are collected before a completed run is ranked',()=>{const n=api.rankings.records.length;e.drop();e.bodies=[];e.ml=50;e.score=86;e.pulp(337,620,4,36);e.ended=true;api.saveRun();check(api.rankings.records.length===n,'saved before collection');tick(420);check(api.rankings.records.length===n+1,'not saved after flow');check(api.rankings.records.some(r=>r.score===86),'final volume missing');check(elements.liveRun.textContent==='86'&&Math.round(e.ml)===86,'HUD disagrees')});
 test('Restart during final drainage preserves the full finished juice result',()=>{const n=api.rankings.records.length;e.drop();e.bodies=[];e.ml=100;e.score=160;e.pulp(337,500,7,60);e.ended=true;elements.restart.trigger('click');check(api.rankings.records.length===n+1&&api.rankings.records.some(r=>r.score===160),'lost pending juice');check(e.ml===0&&!e.started,'reset failed')});

 test('Name remains editable during a run and after pausing',()=>{e.drop();tick(2);check(!elements.playerName.disabled,'locked in run');elements.pause.trigger('click');check(!elements.playerName.disabled,'locked while paused');elements.playerName.value='New Name';elements.resume.trigger('click');check(elements.playerName.value==='New Name'&&!elements.playerName.disabled,'name lost')});
 test('The latest name is used at settlement, without renaming historical results',()=>{elements.playerName.value='Before';e.drop();e.ml=281;e.score=281;elements.playerName.value='After';e.ended=true;api.saveRun();const record=api.rankings.records.find(r=>r.score===281);check(record&&record.player==='After','stale name');elements.playerName.value='Next player';api.sync();check(record.player==='After','history renamed')});
 test('A name changed while the last drops drain is used for that result',()=>{elements.playerName.value='Before';e.drop();e.bodies=[];e.ml=321;e.score=321;e.pulp(337,620,4,36);e.ended=true;api.saveRun();elements.playerName.value='During drain';tick(420);check(api.rankings.records.some(r=>r.score===321&&r.player==='During drain'),'drain name stale')});
 test('Blank current name safely becomes You in a finished result',()=>{e.drop();e.ml=412;e.score=412;elements.playerName.value='   ';e.ended=true;api.saveRun();check(api.rankings.records.some(r=>r.score===412&&r.player==='You'),'blank name not normalized')});
 test('Music and sound toggles are independent and saved',()=>{elements.music.trigger('click');check(api.audio.music&&api.audio.sfx,'first click did not enable music');elements.sound.trigger('click');check(!api.audio.sfx,'sound toggle');check(elements.music.attributes['aria-pressed']==='false','music state');check(Object.keys(storage).includes('fruit-audio-v1'),'audio not saved')});
 test('Live ranking loads in its own iframe document',()=>{check(elements.scoresFrame.getAttribute('src')==='rankings/index.html','no separate ranking');check(!e.paused,'ranking paused play')});
 test('Settings pauses gameplay and restores state on close',()=>{elements.settingsButton.trigger('click');check(e.paused&&elements.settingsDialog.open,'not paused');elements.closeSettings.trigger('click');check(!e.paused&&!elements.settingsDialog.open,'not restored')});
 test('Restart from settings closes menu and restarts the run',()=>{e.drop();elements.settingsButton.trigger('click');elements.restart.trigger('click');check(!elements.settingsDialog.open&&!e.paused&&e.bodies.length===0,'menu restart')});
 test('Opening the guide from settings preserves playable resume state',()=>{elements.settingsButton.trigger('click');elements.guideButton.trigger('click');check(!elements.settingsDialog.open&&elements.guide.open&&e.paused,'guide transition');elements.closeGuide.trigger('click');check(!e.paused,'guide did not resume')});
 test('Fullscreen uses expanded layout when the browser API is absent',()=>{elements.fullscreen.trigger('click');check(stageClasses.has('expanded-game'),'not expanded');elements.fullscreen.trigger('click');check(!stageClasses.has('expanded-game'),'not restored')});
 return {results,renderCalls};
};
